version: "3.8"
services:
  ibc-relayer:
    container_name: ibc-relayer
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./ibc-setup:/app/.ibc-setup
    # command:
    # - npm i -g @confio/relayer@0.10.0
    entrypoint:
      - sh
      - -c
      - |
        npm i -g @confio/relayer@0.10.0 &&
        ibc-setup init &&
        ibc-setup ics20 -v &&
        /bin/sh
    # depends_on: [axelar, wasm]
