/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAxelarGasService__factory } from "./IAxelarGasService__factory";
export { IAxelarGateway__factory } from "./IAxelarGateway__factory";
