/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as axelarCgpSolidity from "./axelar-cgp-solidity";
export type { axelarCgpSolidity };
import type * as axelarGmpSdkSolidity from "./axelar-gmp-sdk-solidity";
export type { axelarGmpSdkSolidity };
