version: "3.8"
services:
  wasm:
    image: cosmwasm/wasmd
    container_name: wasm
    env_file: ".env"
    command: "/root/private/bin/init_and_add_keys.sh"
    volumes:
      - "./bin:/root/private/bin"
    ports:
      - "${CHAIN_RPC_PORT}:26657"
      - "${CHAIN_LCD_PORT}:1317"
      - "26656:26656"
      - "9090:9090"
