/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAxelarExecutable } from "./IAxelarExecutable";
export type { IAxelarGateway } from "./IAxelarGateway";
