/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as axelarCgpSolidity from "./axelar-cgp-solidity";
export * as axelarGmpSdkSolidity from "./axelar-gmp-sdk-solidity";
