/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAxelarGasService } from "./IAxelarGasService";
export type { IAxelarGateway } from "./IAxelarGateway";
