name: Run Tests

on: pull_request

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-22.04]
                arch: [amd64]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install
              run: |
                  npm ci

            - name: Build
              run: |
                  npm run build

            - name: Test
              run: |
                  npm run test
