name: Run Tests

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [amd64]
    # Elasticsearch used by MultiversX test
    services:
      elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:8.12.0"
        env:
          discovery.type: single-node
          xpack.security: "enabled=false"
        ports:
          - "9200:9200"
    steps:
      - name: Download and Install Aptos Binary
        run: |
          wget --no-check-certificate https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v1.0.4/aptos-cli-1.0.4-Ubuntu-22.04-x86_64.zip
          unzip aptos-cli-1.0.4-Ubuntu-22.04-x86_64.zip
          sudo mv aptos /usr/local/bin

      - name: Setup Dependencies for Sui Binary
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Download and Install Sui Binary
        run: |
          wget https://github.com/MystenLabs/sui/releases/download/mainnet-v1.11.2/sui-mainnet-v1.11.2-ubuntu-x86_64.tgz
          tar -xvf sui-mainnet-v1.11.2-ubuntu-x86_64.tgz
          sudo mv ./target/release/sui-test-validator-ubuntu-x86_64 /usr/local/bin/sui-test-validator
          sudo mv ./target/release/sui-ubuntu-x86_64 /usr/local/bin/sui

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Download and Install Multiversx Binary
        run: |
          pip3 install multiversx-sdk-cli==v9.3.0
          mkdir -p /usr/local/multiversx-localnet && cd /usr/local/multiversx-localnet
          mxpy localnet setup
          cd ~
          cp -rf ./packages/axelar-local-dev-multiversx/external.toml /usr/local/multiversx-localnet/localnet/validator00/config
          cp -rf ./packages/axelar-local-dev-multiversx/external.toml /usr/local/multiversx-localnet/localnet/validator01/config
          cp -rf ./packages/axelar-local-dev-multiversx/external.toml /usr/local/multiversx-localnet/localnet/validator02/config
          cd /usr/local/multiversx-localnet
          mxpy localnet start &
          sleep 20

      - name: Cleanup
        run: rm -rf target aptos-cli-1.0.4-Ubuntu-22.04-x86_64.zip sui-devnet-v1.7.0-ubuntu-x86_64.tgz

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        timeout-minutes: 15
        run: |
          nohup sh -c "sui-test-validator" > nohup.out 2> nohup.err < /dev/null &
          nohup sh -c "aptos node run-local-testnet --with-faucet" > nohup.out 2> nohup.err < /dev/null &
          sleep 10
          npm run test
