name: Run Tests for MultiVersX

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [amd64]
    services:
      elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:8.12.0"
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        ports:
          - "9200:9200"
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Install Multiversx Binary
        run: |
          pip3 install multiversx-sdk-cli==v9.3.1
          mxpy localnet setup
          for validator in {00..02}; do
            cp -rf ./packages/axelar-local-dev-multiversx/external.toml ./localnet/validator$validator/config
            cp -rf ./packages/axelar-local-dev-multiversx/enableEpochs.toml ./localnet/validator$validator/config
          done

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:core && npm run build:multiversx

      - name: Test
        timeout-minutes: 15
        run: |
          nohup sh -c "mxpy localnet start" > nohup.out 2> nohup.err < /dev/null &
          sleep 100
          npm run test:multiversx
